# SPDX-License-Identifier: Apache-2.0

name: Spellcheck

on:
  push:
    branches:
      - "main"
    paths:
      - '**.md'
      - '.github/workflows/spellcheck.yml' # This workflow
  pull_request:
    branches:
      - "main"
    paths:
      - '**.md'
      - '.github/workflows/spellcheck.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  spellcheck:
    name: Spellcheck (en_US)
    runs-on: ubuntu-latest
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
         egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: "Checkout"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@cd079c0f6a24c326cb8a4fa5dc8bbf16227990bd # v0.40.0
